expansion:
  uspto:
    - /app/data/aizynth_data/uspto_model.onnx
    - /app/data/aizynth_data/uspto_templates.csv.gz
  ringbreaker:
    - /app/data/aizynth_data/uspto_ringbreaker_model.onnx
    - /app/data/aizynth_data/uspto_ringbreaker_templates.csv.gz
filter:
  uspto: /app/data/aizynth_data/uspto_filter_model.onnx
stock:
  zinc: /app/data/aizynth_data/zinc_stock.hdf5
